spring:
  config:
    import: vault://

  cloud:
    vault:
      uri: ${VAULT_ADDR} # Passed via environment variable
      scheme: http
      token: ${VAULT_TOKEN} # Passed via environment variable
      kv:
        enabled: true
        backend: secret
        default-context: db

  datasource:
    url: jdbc:mysql://localhost:3306/time_ledger_db?useSSL=false&serverTimezone=Asia/Kolkata
    username: ${spring.datasource.username}
    password: ${spring.datasource.password}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQLDialect